-- PUNTO A
--CONCLUSION INTERESANTE
-- Primero tuve que quedarme con los valores de la tabla de notas para la materia que queria
-- Haciendo el JOIN primero y luego quedandome con las que queria, no incluia los valores nulos.
SELECT A.PADRON, NOTAS_7114.NOTA FROM 
ALUMNOS A LEFT OUTER JOIN
(	SELECT N.PADRON, N.NOTA 
 	FROM NOTAS N
 	WHERE CODIGO = 71 AND NUMERO = 14)
AS NOTAS_7114 
ON A.PADRON = NOTAS_7114.PADRON;

--PUNTO B
SELECT DISTINCT TERCERO.P3 PADRON, ALUMNOS.APELLIDO APELLIDO FROM
((SELECT DISTINCT PADRON P3, CODIGO C3, NUMERO N3, NOTA NOTA3 FROM NOTAS WHERE NOTA >= 5) AS TERCERO
 INNER JOIN
(SELECT * FROM
(SELECT DISTINCT PADRON P1, CODIGO C1, NUMERO N1, NOTA NOTA1 FROM NOTAS WHERE NOTA >= 5) AS PRIMERO
INNER JOIN
(SELECT DISTINCT PADRON P2, CODIGO C2, NUMERO N2, NOTA NOTA2 FROM NOTAS WHERE NOTA >= 5) AS SEGUNDO
ON PRIMERO.P1 = SEGUNDO.P2 AND PRIMERO.NOTA1 <> SEGUNDO.NOTA2) AS AUX 
ON TERCERO.P3 = AUX.P1 AND TERCERO.NOTA3 <> AUX.NOTA1 AND TERCERO.NOTA3 <> AUX.NOTA2), ALUMNOS
WHERE TERCERO.P3 = ALUMNOS.PADRON;

-- PUNTO C
-- SE ASUME QUE SE APRUEBA CON 4
-- SE ASUME QUE SI UN ALUMNO NO RINDIO UNA MATERIA (SU NOTA ES NULL) NO APROBÓ LA MATERIA
-- LA MATERIA APROBADA ES AQUELLA QUE UN ALUMNO LA RINDIO Y SU NOTA ES MAYOR A 4
SELECT A.PADRON 
FROM ALUMNOS A LEFT OUTER JOIN
	(SELECT N1.PADRON AS PADRON, N1.NOTA AS NOTA_7114, N2.NOTA AS NOTA_7115
	FROM
	NOTAS N1 LEFT OUTER JOIN NOTAS N2
	ON N1.PADRON = N2.PADRON AND (N1.CODIGO = 71 AND N1.NUMERO = 14) AND (N2.CODIGO = 71 AND N2.NUMERO = 15)
	WHERE N1.CODIGO = 71 AND N1.NUMERO = 14) AS NOTAS_7114_7115
ON A.PADRON = NOTAS_7114_7115.PADRON
WHERE NOTAS_7114_7115.NOTA_7114 >= 4 AND (NOTAS_7114_7115.NOTA_7115 < 4 OR NOTAS_7114_7115.NOTA_7115 IS NULL);

-- PUNTO D
SELECT A.PADRON, A.APELLIDO FROM ALUMNOS A INNER JOIN
(SELECT PADRON, COUNT(DISTINCT NUMERO) AS CANTIDAD_NOTAS_75 FROM NOTAS WHERE CODIGO  = 75
GROUP BY PADRON
HAVING COUNT(DISTINCT NUMERO) = (SELECT COUNT(*) FROM MATERIAS WHERE CODIGO = 75)) AS TODOS
ON A.PADRON = TODOS.PADRON;

-- PUNTO E
SELECT A.PADRON, A.APELLIDO FROM ALUMNOS A INNER JOIN
(SELECT PADRON, COUNT(*) AS CANTIDAD_APROBADAS FROM 
(SELECT DISTINCT PADRON, CODIGO, NUMERO, NOTA FROM NOTAS WHERE NOTAS.NOTA >= 4) AS APROBADAS_SIN_REPETIR
GROUP BY PADRON 
HAVING COUNT(*) = (SELECT COUNT(*) FROM MATERIAS)) AS APROBADOS
ON A.PADRON = APROBADOS.PADRON
ORDER BY PADRON;